### ISSUE TITLE
User Story 8: Navigation Bar

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#15]
## Value Proposition

As a user 
I want to see a nav bar 
in order to be able to navigate easily through the application.

## Description

![Bildschirmfoto 2024-05-03 um 10 40 21](https://github.com/benediktbrenk/budget-app/assets/80427431/3f5a2ebb-8968-4558-a053-92adcbf0c382)

## Acceptence Criteria

- The application displays a navigation bar at the bottom of each page.
- The navigation bar includes links to the esssential pages of the application: HomePage, ReportsPage and NewEntryPage.
- Each navigation link is visually distinguishable and clearly labelled, providing intuitive navigation for users.
- When a user clicks on a navigation link, the application navigates to the corresponding page.
- The navigation bar remains consistently visible and accessible as the user scrolls through the application's content.
- The active page is highlighted by color in the navigation bar.

## Tasks

- [ ] Create and implement`Navbar` component
- [ ] Implement the component at the bottom of every page with the highest z-index
- [ ] Add navigation links for HomePage, ReportsPage and NewEntryPage
- [ ] Create a color variable and apply it to the link that corresponds to the active page
- [ ] Delete the `Back` link on all pages

**Comment by Larissartoricader** [comment]
Suggestion as Task: Make sure that all content provided on the _transaction page_ is visible if the nav bar is fixed on that page; otherwise, the last information at the bottom of the page will be covered by the nav bar. (🫣 We just had the same issue)

**Comment by marcelherr** [comment]
Thank you for the hint, we will take that into consideration.

**Comment by arne-witteler** [comment]
Except for the last acceptance criteria, everything LGTM
