### ISSUE TITLE
User Story 9: Redesign Transaction Card

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#16]
## Value Proposition

As a user
I desire visually appealing 'Transaction Cards' categorized by type
in order to enhance the clarity of where my finances are allocated.

## Description

![Bildschirmfoto 2024-05-03 um 13 06 29](https://github.com/benediktbrenk/budget-app/assets/80427431/3add9aad-11d9-41a9-be87-b820621ef1a6)

## Acceptence Criteria

- Each transaction card should be visually different, with colors corresponding to the category.
- The transaction card name should be bold so thats easy to read.
- The transaction card are visually appealing with a modern and clean design that improve the user experience.

## Tasks

- [ ] Create freature branch `feature/redesign-transaction-card`
- [ ] Format `transaction.name` 
- [ ] Implement dynamic color code for each card
- [ ] Redesign the `transaction cards`

**Comment by nattenhagen** [comment]
Nice Work :)! The colors make it easy and intuitiv to have an overview of my income and expenses :) I like that you also marked the categories with similar colors! But in the text it says the box should be grey? Anyhow, I like the idea with the colored categories <3.
