### ISSUE TITLE
Dev Story 12: Backend Read 

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#19]
## Value Proposition

As a user,
I want to get access to my data from a database through the application,
so that I have permanent access to my data regardless of the device.

## Description

This user story focuses on enabling users to access the database through the application to retrieve and display their entries. By leveraging this functionality, users can seamlessly interact with their data stored in the cloud, ensuring accessibility across various devices.

## Acceptence Criteria

- The application provides a user interface for read data.
- When application starts, it sends a request to the backend.
- The backend receives the request and validates the data for integrity and completeness.
- The displayed entries must accurately reflect the data stored in the backend database, updating dynamically if changes occur.
- The backend database access functionality should be efficient and reliable, with minimal latency and downtime.

## Tasks

- [ ] Create feature branch `feature/backend-read`
- [ ] Create a database `budget-app` with a collection named`transactions` on mongoDB 
- [ ] Write a `schema` to create a ` transaction model` that can interact with the database
    - [ ] `id, name, amount, currency, date, description, category, paymentMethod, direction`
- [ ] Integrate error handling in the backend by defining clear error codes
    - [ ] Use appropriate HTTP status codes
    - [ ] Provide descriptive error messages
    - [ ] Handle exceptions and edge cases
    - [ ] Implement error logging mechanisms.
- [ ] Create return confirmation message to the application upon successful data addition
- [ ] Install package mongoose and use it to connect to the database
- [ ] Create a .env.local file and fill it with `MONGODB_URI=mongodb+srv://:@/?retryWrites=true&w=majority` and keep the information safe by including it in the `.gitgnore` file
- [ ] Implement the data base connection logic in the backend to establish connection with mongoDB database

**Comment by Jessica-Windoffer** [comment]
Wow, described really detailed! Great Work!

Only question: What about the API-Routes? Do you have that on the screen?
