### ISSUE TITLE
User Story 1: Expense list

### ISSUE THREAD

**Issue by benediktbrenk** [benediktbrenk/budget-app#2]
## Value proposition
As a budget-conscious user,
I want to have an overview of my expenses,
so that I can keep track of them.
## Description

![US 1](https://github.com/benediktbrenk/budget-app/assets/155526766/edec35a7-6aaa-4b77-9353-a02a0a439a3e)

## Acceptance criteria
- The user must be able to view a consolidated overview of all their expenses in a clear and comprehensible manner.
- The list displays expense details such as:
  - `amount`
  - `currency`
  - `date of entry`
- The list supports vertical scrolling to accommodate multiple entries.
## Tasks
- [x] create feature branch `feature/expense-list`
- [x] create dummy data 
- [x] create component TransactionCard that shows example text `name, amount, currency, date of entry`
- [x] implement one item of the dummy data on the card
- [x] create TransactionList Component that shows all TransactionCard items
- [x] create component Header that displays the title of the page "Transactions"
