### ISSUE TITLE
User Story 12: Backend Create Update Delete

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#25]
## Value Proposition

As a user,
I want to be able to create, update and delete data and send it to the backend database through the application,
so that my data is stored in a cloud and I have access to my data regardless of the device.

## Acceptence Criteria

- Creating new data, updating and deleting data work successfully with the database.
- After creating, updating or deleting the UI is rerendered with up-to-date data.
- If there are any errors during the update (create, delete) process, such as invalid input or database connection issues, the backend sends an appropriate error response to the application.

## Tasks

- [ ] Create feature branch `feature/backend-cud`
- [ ] Refactor the existing add function with a `POST` method to send new data transactions
- [ ] Refactor the existing edit function with a `PUT` method to update data transactions
- [ ] Refactor the existing delete function with a `DELETE` method to delete data transactions
- [ ] In the handler function add functions to receive POST, PUT and DELETE requests and change entries in the database (via `transactions.findByIdAndUpdate()`, `transactions.findByIdAndDelete()`)
- [ ] Integrate error handling in the backend using common HTTP status codes

**Comment by Roland-Hufnagel** [comment]
LGTM. Additional information could be the api routes, you want to implement, setting up a database e.g. with mongo db atlas, creating a schema and a model.
