### ISSUE TITLE
User Story 14: Structure transaction list

### ISSUE THREAD

**Issue by benediktbrenk** [benediktbrenk/budget-app#28]
## Value proposition

As a user
I want to view the transaction list sorted chronologically and structured by month and year
in order to easily track my financial activity over time and identify spending patterns.

## Description

<img width="383" alt="US 14" src="https://github.com/benediktbrenk/budget-app/assets/155526766/caa19e9e-e2d5-4065-855c-724f3d2a0882">

## Acceptance criteria

- [ ] Transactions should be sorted chronologically within each month.
- [ ] Each month's transactions should be clearly separated and indicated with a visible headline.
- [ ] Empty sections should be handled with placeholders.

## Tasks

 - [ ] Implement sorting algorithm to organize transactions 
      - [ ] chronologically
      - [ ] by month and year.
  - [ ] Create visual separation between transaction groups.
  - [ ] Handle empty sections with appropriate placeholders.

**Comment by Roland-Hufnagel** [comment]
Hi. I do not understand what you mean with empty sections placeholders. Can you please clarify it a bit more?
