### ISSUE TITLE
User Story 3: Expense Entry

### ISSUE THREAD

**Issue by benediktbrenk** [benediktbrenk/budget-app#3]
## Value Proposition

**As a** budget-conscious user,

**I want to** view the details of each of my expenses,

**so that** I can understand the specifics of where my money is going and ensure accuracy in my financial tracking.

## Description

<img width="401" alt="Bildschirmfoto 2024-04-25 um 11 58 47" src="https://github.com/benediktbrenk/budget-app/assets/155526766/31c19dc1-b14d-4012-8c6b-eaff8ecd8a1d">

## Acceptance Criteria

- The user must be able to select an individual expense from their overview to view its detailed information.
- The detail view should include the expense amount, date of transaction, category (e.g., utilities, groceries), and any associated notes or descriptions.
- The app should ensure that the transition from the expense overview to the detail view and vice versa is seamless and intuitive.
- The user should have the option to return to the expense overview from the detail view without losing their place or having to navigate through multiple screens.

## Tasks

- [ ] create feature branch `feature/expense-detail-view`
- [ ] create ExpenseDetails page
- [ ] implement component Header displaying the name of the detailed Expense
- [ ] create component ExpenseCardDetails
- [ ] create link from ExpensePreviewCard to ExpenseCardDetails Page 
- [ ] create a button that links to the Expense List page
