### ISSUE TITLE
User Story 14 : Redesign Transaction Details Card

### ISSUE THREAD

**Issue by H-Alguen** [benediktbrenk/budget-app#33]
## Value Proposition

As a user,
I want to redesign on the transaction details card,
so that the information is more readable.

## Description
![Redesign TransactionDetails](https://github.com/benediktbrenk/budget-app/assets/161036202/320e8caa-a935-41a6-84bf-ecb9f85be417)

## Acceptence Criteria

- The transaction details card should be well structured for better readability
- The transaction details card has appropriate headings for the information
- The design should be visually appealing

## Tasks

- [ ] Create feature branch `feature/redesign-transaction-details-card
- [ ] Do some research for appealing design
- [ ] redesign Content in the DetailsContainer and in a similar design like the transaction preview
- [ ] Display Data with labels `title, amount, date, category, description`
- [ ] Create more space between different Data-information
- [ ] Redesign the` edit` and `delete` button and appropriate color.
- [ ] rename the styled components

**Comment by Jessica-Windoffer** [comment]
LGTM 😎

Just one tiny suggestion: You want to `Display Data with labels `title`, `amount`, `date`, `category`, `description``. But you also want to label `direction` as shown in the wireframe 😊
