### ISSUE TITLE
User Story 15 : Redesign Edit Page

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#34]
## Value Proposition

As a user,
I want to edit a transaction with a modal on the details page,
so that the user experience is better.

## Description

![Bildschirmfoto 2024-05-08 um 16 13 54](https://github.com/benediktbrenk/budget-app/assets/80427431/4ecafe97-0729-4d62-8553-22d0b798b613)

## Acceptence Criteria

- The Edit form is a modal that shows up on the transaction details page when edit button is clicked
- The transaction detail card is not visable when edit button is clicked
- When Save/ update button is clicked the edit form modal disappers and the updated transaction details card is displayed
- When the cancel button is clicked the edit form modal disappears and the orginal transaction details card is displayed

## Tasks

- [ ] Create feature branch `feature/redisgn-edit-page`
- [ ] Render the` editForm` component as a `modal`on the details page
- [ ] create a state that manage the visabillity of the `edit modal`
- [ ] Create function that shows the `modal` in modern way when edit button is clicked
- [ ] Rename styled components

**Comment by Jessica-Windoffer** [comment]
LGTM overall but I have one criteria why you have a ✔️ at the moment:

As a User I would expect that - when I edit a existing transaction, the already given parameters such as `title`, `amount, `date` etc. are already pre-filled so that I - as a user - do not have to type in everything again and just have to change want to. Maybe you could change your User Story to meet that criteria 😊
