### ISSUE TITLE
User Story  16: Gobal Button Standardization

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#35]
## Value Proposition

As a user,
I want to see that every button is designed the same,
so that the application gets a better look and the user experience is enhanced 

## Description

- no description or wireframe needed

## Acceptence Criteria

- The buttons look and behave the same on every page 
- The links have a similar design as buttons
- Clicking on a button or a link triggers the expected function
- The buttons should have a meaningful color

## Tasks

- [ ] Create feature branch `feature/gobal-button
- [ ] Create a resuable `button` component with consistent styling and behavior
- [ ] Implement the functionality to recive `delete` , `edit` and `save` prop, each with respective color code
- [ ] Create a `link` component styled similar to the button component
- [ ] Integrate the `button` component wherever buttons are used across the application
- [ ] Integrate the `link` component for navigation wherever it is used

**Comment by nattenhagen** [comment]
LGTM. The only thing I would recommend is to maybe make the Budget Overview more distinct from the filter and the clear button :).
