### ISSUE TITLE
User Story 3: Expense Entry

### ISSUE THREAD

**Issue by benediktbrenk** [benediktbrenk/budget-app#4]
## Value Proposition

**As a** budget-conscious user,

**I want to** easily enter details of my expenses as they occur,

**so that** I can accurately track my spending without forgetting or missing out on recording any expenses.

## Description

<img width="585" alt="Bildschirmfoto 2024-04-25 um 11 52 31" src="https://github.com/benediktbrenk/budget-app/assets/155526766/36e6871c-9e1f-487e-94c6-d46dc93e02ec">

## Acceptance Criteria

- The user must be able to quickly access the expense entry feature from the main interface of the app.
- The app should provide a simple and intuitive form for entering expense details, including amount, category (e.g., food, transportation, bills), date, and an optional description.
- The expense entry form must offer a selection of common expense categories, as well as the ability to add a new category if the existing ones do not fit the user's needs.
- After entering an expense, the user should receive immediate visual confirmation that the entry has been successfully added to their expense log.
- The app should ensure that all data entered is saved promptly and accurately to prevent loss of information, especially in cases of sudden app closure or device issues.

## Tasks

- [ ] create feature branch `feature/expense-entry`
- [ ] create NewEntry page
- [ ] create component ExpenseEntryForm to add new expenses
- [ ] create a function to push the User back to the Expense List Page 
- [ ] create a state to store the expense data

**Comment by Jessica-Windoffer** [comment]
Suggestions for improvements:
1. Direction field would be nicer if it would have a default value "Please select a option" to  avoid that I submit an entry that is supposed to be a income but is submitted as expense just because it is pre-defined.
2. The amount field is clickable not only into the positive number range, but also into the negative number range. Therefore as soon as you submit the entry form and expense is set, in the overview there is "- -" shown.
3. You label the fields in english, but have a german type input field (in english the structure is: mm/dd/yyyy)
