### ISSUE TITLE
User Story 17: Decimal Numbers

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#42]
## Value Proposition

As a user, 
I want to type in dezimal number in the input field,
so that the numbers and calculations are exact.

## Description

No description or image needed

## Acceptence Criteria

- The input field should allow users to enter decimal numbers
- Decimal numbers should be displayed wherever they are required 

## Tasks

- [ ] Create feature branch `feature/decimal-numbers`
- [ ] Implement functionality to accept decimal numbers in the input fields
- [ ] Make sure the `Account Balance` works with decimal numbers correctly
