### ISSUE TITLE
User Story 18: Buttons as category filter

### ISSUE THREAD

**Issue by benediktbrenk** [benediktbrenk/budget-app#43]
## Value proposition

As a user, I want to use colored buttons as category filters on the homepage, instead of traditional checkboxes, in order to quickly and intuitively filter content.

## Description

<img width="233" alt="US 18" src="https://github.com/benediktbrenk/budget-app/assets/155526766/444b29fc-abef-4766-94e3-83e5ca8338c4">

## Acceptance criteria
- [ ] Buttons are colored according to the respective category's  color
- [ ] A click on the on the button filters the respective categories.
- [ ] The category filter is usable for the Dashboard and the Report Page
    - [ ] On the Dashboard the filtered transactions are shown in the list
    - [ ] On the Report Page the total amount of the transactions in the category is shown in the charts

## Tasks
- [ ] Create a component CategoryFilter.
- [ ] Refactor the filter function to work with the filter buttons
- [ ] Use a CategoryColors array in Utils to display the buttons in the color of each category
- [ ] Implement a headline "Categories"
- [ ] Remove the category field from the Filter Form
