### ISSUE TITLE
User Story 19: "Go to top"-Button

### ISSUE THREAD

**Issue by benediktbrenk** [benediktbrenk/budget-app#44]
## Value proposition

As a user, I want to have a "Go to Top" button on the page so that I can quickly and easily return to the top of the page.

## Description

<img width="287" alt="US 19" src="https://github.com/benediktbrenk/budget-app/assets/155526766/d160507b-f363-4efb-943b-85b0cef1f81d">

## Acceptance criteria

- [ ] The "Go to Top" button is positioned at the bottom of the page.
- [ ] When the button is clicked, the page automatically slides up to the top.
- [ ] The button maintains its position and remains visible even when the user has scrolled far down the page.
- [ ] The button is not displayed when the user is already at the top of the page.

## Tasks

- [ ] Create a branch `go-to-top`
- [ ] Implement the "Go to Top" button into the page design.
- [ ] Add functionality to scroll the page to the top when the button is clicked.
- [ ] Ensure the button remains visible and correctly positioned, even as the user scrolls.
- [ ] Try react-scroll-up-button or your own JS and CSS to meet the requirements

**Comment by arne-witteler** [comment]
LGTM! maybe you want a `back button` on the `detail page` as well, that brings the user back to the last page and same position.
