### ISSUE TITLE
Developer Story 2: Global CSS Styles for Fonts, Colors and Boxes

### ISSUE THREAD

**Issue by benediktbrenk** [benediktbrenk/budget-app#46]
## Value proposition

As a frontend developer
I want to define global styles
in order to ensure consistent presentation of fonts and colors across the application.

## Acceptance criteria

- [ ] Three complementary fonts should be defined: one for headings, one for body text, and one for emphasis.
- [ ] Font sizes and styles should be uniformly set for various elements of the user interface to achieve consistent presentation.
- [ ] The app will acquire a visual identity through a unified color scheme

   1. [ ] Primary Color
   2. [ ] Secondary Color
   3. [ ] Accent Color
   4. [ ] Surface Color
   5. [ ] Background Color
   6. [ ] Error Color

- [ ] There will be a consistent box shadow.
- [ ] The mentioned styles must be responsive.

## Tasks

- [ ] Create global variables for all aspects above mentioned in styles.js.
- [ ] Implement the variables in the various elements and components.
- [ ] Research on visual appealing color schemes.
