### ISSUE TITLE
User Story 20: Header

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#47]
## Value Proposition

As a user,
I want see a header on every page,
so that I can see the name and the logo of the application.

## Description

![Bildschirmfoto 2024-05-13 um 10 06 16](https://github.com/benediktbrenk/budget-app/assets/80427431/e3d26b8f-5588-4169-9144-bbb22f07d4bb)

## Acceptance Criteria

- The header is visible on every page
- The header contains the name and the logo
- The header has a backgroundcolor

## Tasks

- [ ] Create feature branch `feature/header`
- [ ] Create `header` component
- [ ] Display the `name` and the `logo` in the component
- [ ] Render the `header` component on every page
- [ ] Create color variable `--header-background-color`
