### ISSUE TITLE
User Story 21: Dark Mode 

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#48]
## Value Proposition

As a user,
I want to see a dark mode button,
so that I can reduce eye strain in low-light environments.

## Description

![Bildschirmfoto 2024-05-13 um 10 27 45](https://github.com/benediktbrenk/budget-app/assets/80427431/8901f9cf-4867-40fb-bafa-ecb4c8126e33)

## Acceptance Criteria

- The dark mode button is clearly visible and accessible.
- Switching between modes changes the color scheme of the application.
- When dark mode button is clicked the button changes to light mode icon.
- All elements of the website are adjusted to maintain visibility in the dark mode.

## Tasks

- [ ] Create feature branch `feature/dark-mode`
- [ ] Create a `darkMode` Component
- [ ] Use meaningfull `icon `for the toggle button
- [ ] Place `darkMode` button on the right side in the header
- [ ] Change the icon when dark mode is active to light mode icon
- [ ] Create dark mode theme and make sure it works when button is clicked
