### ISSUE TITLE
User Story 22: Action icons on transaction card

### ISSUE THREAD

**Issue by benediktbrenk** [benediktbrenk/budget-app#49]
## Value proposition

As a user
I want to have easy access to essential actions like editing, deleting, and viewing details,
in order to efficiently manage transactions without unnecessary navigation.

## Description

<img width="388" alt="US" src="https://github.com/benediktbrenk/budget-app/assets/155526766/249e58e6-d2b5-4c85-88a2-f0a5ebefdf52">

## Acceptance criteria

- [ ] Action icons for edit, delete, view details are displayed on the transaction card.
- [ ] Clicking on each action icon triggers the corresponding action.
- [ ] The icons are visually distinct and easily recognizable.

## Tasks

- [ ] Choose appropriate icons for editing, deleting, and viewing details.
- [ ] Add functionality to handle clicks on each action icon.
- [ ] Implement the action icons on the transaction card component.
- [ ] Redesign the transaction card so that it has the category color as a soft background

**Comment by ahohnsen** [comment]
Good idea! Saving users from unnecessary clicks is always beneficial. :) 

Additionally, for your wireframes, I recommend using 'real' content instead of placeholder text like _Lorem ipsum_. This approach offers many advantages, including:

- **User-centered design** - Real content allows for more precise adjustment of the design to meet user needs.
- **Early detection of design problems** - Real content can help identify layout issues and other design challenges early on.
- **Avoiding surprises** - Using real data reduces the risk of unexpected problems during later implementation.
