### ISSUE TITLE
User Story 4: Edit Expense

### ISSUE THREAD

**Issue by benediktbrenk** [benediktbrenk/budget-app#5]
## Value Proposition

**As a** budget-conscious user,

**I want to** be able to edit the details of an expense,

**so that** I can correct mistakes or update the information to ensure my expense tracking is accurate.

## Description

<img width="774" alt="Bildschirmfoto 2024-04-25 um 12 14 11" src="https://github.com/benediktbrenk/budget-app/assets/155526766/b2f84d26-6001-483b-8880-5bbaec653ef7">

## Acceptance Criteria

- The user must be able to easily find and select an expense they wish to edit from their expense log or overview.
- Upon selecting an expense to edit, the user should be presented with the current details of the expense (amount, category, date, description, payment method) in an editable format.
- The app should allow the user to make changes to any of the expense details, including the amount, category, date, description, and payment method.
- After editing, the user should be able to save the updated expense details with a clear and straightforward action, such as a "Save" or "Update" button.
- The app must immediately reflect the changes in the expense overview and any related summaries or reports, ensuring the edits are accurately incorporated into the user's financial tracking.
- The user should receive visual or textual confirmation that their changes have been saved successfully, preventing confusion or uncertainty about the expense's status.

### Tasks

- [ ] create feature branch `feature/edit-expense`
- [ ] create edit Button on ExpenseCardDetails page 
- [ ] create EditPage that implements the component ExpenseEntryForm so that it edits the seletected entry
- [ ] create a function to push the User back to the Expense List Page rendering the edited entry
