### ISSUE TITLE
User Story 23: Color Theme 

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#50]
## Value Proposition

As a user,
I want to see a appropriate color theme,
so that it looks consistent and professional

## Description

No description or image needed.

## Acceptance Criteria

- The color theme is implemented consistently across all pages of the web application
- The chosen color palette aligns with the logo and design

## Tasks

- [ ] Create feature branch `feature/color-theme`
- [ ] Implement the color palette to the root
- [ ] Make sure the right `color variables` are used in every required place
