### ISSUE TITLE
User Story 23: Profile Page

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#56]
## Value Proposition

As a user,
I want to access and manage my profile information, 
so that I can keep my personal details up to date and customize my user experience.

## Description

![Image](https://github.com/benediktbrenk/budget-app/assets/80427431/a6c55495-9e89-4491-b639-8692fa9180eb)

## Acceptence Criteria

- The profil page is accesible via the profile icon in the header
- Users can see their username, email address.
- Edit function allows to change their profile information and login credentials.
- Changes to profile information can be saved or canceled with buttons.
- A Dark Mode switch can toggle between color themes.

## Tasks

- [ ] Create a `Profil Page` that shows `username`,`email address` and `edit button`
- [ ] Link the `Profil Page` to the `header`
- [ ] Create a function to edit the user information
- [ ] Create a fucntion to edit the login credentials
- [ ] Render `Dark Mode` component on profil page

**Comment by nattenhagen** [comment]
Nice Feature :) Will it also be possible in future to add your own profil pic?
