### ISSUE TITLE
User Story 5: Delete Expense

### ISSUE THREAD

**Issue by benediktbrenk** [benediktbrenk/budget-app#6]
## Value Proposition

**As a** budget-conscious user,

**I want to** have the ability to delete any expense entry,

**so that** I can keep my expense log accurate and free of errors or irrelevant entries.

## Description

<img width="734" alt="Bildschirmfoto 2024-04-25 um 12 45 26" src="https://github.com/benediktbrenk/budget-app/assets/155526766/162cec8c-c99d-4b37-ad33-856f3cfb17f7">
wireframes

## Acceptance Criteria

- The user must be able to easily identify and select the expense they wish to delete from their expense log or overview.
- The app should prompt the user for confirmation before deleting an expense, to prevent accidental deletions.
- Upon confirmation, the expense should be permanently removed from the user's expense log, with immediate effect.
- The app must update all relevant views, summaries, and reports to reflect the removal of the deleted expense, ensuring the user's financial overview remains accurate.
- The deletion process should be straightforward and require minimal steps, enhancing the user experience by making expense management more efficient.
- After a successful deletion, the user should receive a clear notification or visual indication that the expense has been successfully removed.

## Tasks

- [ ] create feature branch `feature/delete-expense`
- [ ] create a button to delete the chosen expense
- [ ] create a component Modal including buttons to cancel or confirm delete
- [ ] create a state to toggle between Details and Modal
