### ISSUE TITLE
User Story 25: Toast Message

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#65]
# User Story 25: Toast Message

## Value Proposition

As a user,
I want be informed when I take actions like logging in, adding, updating or deleting 
so that I can be sure the actions I have taken are successful.

## Description

![Bildschirmfoto 2024-05-16 um 16 31 02](https://github.com/benediktbrenk/budget-app/assets/80427431/20a16012-973a-4ad9-abb0-860d7559ab4e)

## Acceptance Criteria

- When an action like logging in,adding, updating or deleting is taken, a toast message should appear to confirm the action
- The toast message should disappear after a few secounds
- When multipe toast messages are shown they are stacked

## Tasks

- [ ] Create feature branch `feature/toast-message`
- [ ] Create `ToastMessage` component with addjustable message content
- [ ] Display the appropriate message when the corresponding action is completed 
- [ ] Handle stacking of multiple `toast messages` to prevent overlapping
