### ISSUE TITLE
User Story 27: Redesign Balance Board

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#67]
## Value Proposition

As a user,
I want to see a Balance Banner on the top of the landing page,
so that I have always a complete overview

## Description

![Bildschirmfoto 2024-05-16 um 16 31 16](https://github.com/benediktbrenk/budget-app/assets/80427431/6eae5b02-bb02-4084-99af-5d36ad1ba22c)

## Acceptance Criteria

- The Balance Banner is alway visible on the landing page
- The information shown is visible at a glance
- The Banner is a one-liner
- The banner shows the complete amount,income and expenses

## Tasks

- [ ] Create feature branch `feature/balance-banner`
- [ ] Redesign the `AccountBalance` component
- [ ] Rename the component to `BalanceBanner`
- [ ] Make sure the design meets the application styling
