### ISSUE TITLE
User Story 28: Implement stylish calendar form

### ISSUE THREAD

**Issue by benediktbrenk** [benediktbrenk/budget-app#69]
## Value proposition

As a user, I want an interactive calendar to easily select and manage transaction dates.

## Acceptance criteria

- [ ] When no date is selected, the calendar remains in its default state.
- [ ] It is possible to select a single date or a span.
- [ ] The calendar allows for easy navigation between months and years.
- [ ] Selected dates are displayed correctly and can be saved into the filter.

## Tasks

- [ ] Integrate react-day-picker into the project.
- [ ] Implement functionality for selecting dates and times.
- [ ] Apply basic styling to the calendar.
- [ ] Link selected data to the corresponding functions of the application.

**Comment by Xristof23** [comment]
LGTM!
