### ISSUE TITLE
User Story 6: Search and Filter

### ISSUE THREAD

**Issue by benediktbrenk** [benediktbrenk/budget-app#7]
## Value Proposition

**As a** budget-conscious user,

**I want to** be able to search for specific expenses and apply filters,

**so that** I can quickly find exactly what I'm looking for and analyze my spending patterns more effectively.

## Description

<img width="899" alt="Bildschirmfoto 2024-04-25 um 15 32 31" src="https://github.com/benediktbrenk/budget-app/assets/155526766/1cb60d8f-be36-4b3e-bcb8-50f6d956c144">

## Acceptance Criteria

- [ ] The user must be able to access a search function easily from the main interface of the app to locate specific expenses by keywords, such as category, description, or date.
- [ ] The app should provide a comprehensive filtering system that allows users to refine their expense view based on categories, payment methods, date ranges (e.g., day, week, month, year), and amount ranges.
- [ ] The search results should be displayed promptly and clearly, highlighting the matching expenses based on the user's search query or applied filters.
- [ ] The user should have the option to combine multiple filters for more precise search results, such as finding all dining expenses in a particular month that exceeded a certain amount.
- [ ] After applying a search or filter, the user must be able to easily clear or modify their search criteria to adjust the displayed results.
- [ ] The search and filter feature should include a visual indication or summary of the applied criteria, helping users understand why certain expenses are displayed.

## Tasks

- [ ] create feature branch `feature/search-and-filter`
- [ ] create component SearchBar
- [ ] create Filter component with dropdown menu and `date range, amount range, category, income expense, all `
- [ ] implement SearchBar and Filter components on ExpenseList Page
