### ISSUE TITLE
User Story 30: Redesign Report Page

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#70]
## Value Proposition

As a user,
I want a see a a modern report page,
so that I see a consistent styling of the application.

## Description

No description or wireframe needed.

## Acceptance Criteria

- The redesigned report page should have a modern look
- It should be user friendly and intuitive to navigate
- The redesign should meet the styling from the application

## Tasks

- [ ] Create feature branch `feature/redesign-reports-page`
- [ ] Redesign the` Reports Page` so that the user experience is enhanced
- [ ] Redesign the `Filter` options
