### ISSUE TITLE
User Story 33: Tablet Design

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#71]
## Value Proposition

As a user
I want a tablet friendly design,
so that I have an optimized user experience on tablet devices.

## Description

![Bildschirmfoto 2024-05-17 um 11 04 01](https://github.com/benediktbrenk/budget-app/assets/80427431/9ff78e5f-90f1-49d2-a237-4ea933a88bcb)

## Acceptance Criteria

- The design is responsive and optimized for tablet devices
- Navigation menus and buttons are large enough for touch interaction
- Content layout adjusts for different tablet screen sizes

## Tasks

- [ ] Create feature branch `feature/tablet`
- [ ] Change the order of components 
- [ ] Optimize content layout for tablet viewing

**Comment by arne-witteler** [comment]
nice wireframe 😄 maybe add a step for media queries?
