### ISSUE TITLE
User Story 34: Desktop Design

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#72]
## Value Proposition

As a user
I want a desktop friendly design,
so that I can see more information at once to have an optimized user experience with desktop or laptops computers

## Description

![Bildschirmfoto 2024-05-17 um 11 03 55](https://github.com/benediktbrenk/budget-app/assets/80427431/9b859c1d-a21c-4d6d-b111-30333e28fbd7)

## Acceptance Criteria

- The design is responsive and optimized for desktop devices
- Navigation menus and buttons are positioned for easy access with a mouse
- Content layout makes efficient use of larger desktop screen sizes
- Hover and cursor effects are implemented on button and links

## Tasks

- [ ] Create feature branch `feature/desktop`
- [ ] Optimize content layout for desktop viewing
- [ ] Change the order of components

**Comment by nattenhagen** [comment]
Short and cohesive Userstory :) I guess the acceptance criteria for responsiveness is also included in your task!
