### ISSUE TITLE
User Story 31: Redesign Login/Logout

### ISSUE THREAD

**Issue by H-Alguen** [benediktbrenk/budget-app#73]
## Value Proposition
As a user
I want to have a responsive login/logout experience,
so that I can get to grips with the operation better

## Description
![Bildschirmfoto 2024-05-17 um 11 15 21](https://github.com/benediktbrenk/budget-app/assets/161036202/316952b6-f658-4a23-8983-f78eb30dfa6d)

## Acceptence Criteria
- Easy way to login with a Login Button
- Short test to guide you through the login
- After Login the login button change to a avatar Icon
- Dropdown on the Avatar with link to the ProfilePage and a Logout button

## Tasks
- [ ] Create feature branch `feature/login-logout`
- [ ] Add a Avatar Icon instead of the Logout button
- [ ] Create a dropdown Menu with 2 Items 1.a Link to ProfilePage and 2.Logout Button
- [ ] After Logout push the user back to the LoginPage

**Comment by nattenhagen** [comment]
very nice feature :)
