### ISSUE TITLE
User Story 36: Redesign Details Page Delete Modal

### ISSUE THREAD

**Issue by marcelherr** [benediktbrenk/budget-app#87]
## Value Proposition

As a user
I want a to see a modal when i click on delete button,
so that I have the option to cancel the delete progess.

## Description

No description or image needed.

## Acceptance Criteria

- The modal is only displayed when the user clicks on delete
- The modal shows a question: Are you sure?
- When the user cicks on cancel the modal disappears

## Tasks

- [ ] Create feature branch `feature/details-delete-modal`
- [ ] Use the `Modal` component
- [ ] Make sure the`Modal` has an `delete` and `cancel` button

**Comment by ladydarkja** [comment]
Hey, nice feature! I'm pretty sure, the users will profit a lot from this double check before deleting data.

I found a couple of typos I'd recommend you to fix:
in Value proposition: 
- i -> I
- progess -> progress

in acceptance criteria:
- cicks -> clicks

in tasks:
- an -> a 

also, the value proposition should be a short and easy overview intention, therefore it's recommended to use simple language. Please consider changing the technical term "modal" to "confirmation message".

Also, I am missing a wireframe to give a visual idea of how the confirmation message looks, since userstories will be seen by non-developers that might not know how a modal looks like. Please add a wireframe to display your idea.

Furthermore, the acceptance criteria don't use specific technical terms either, please make it less technical and add the clickable answer-options for the question "are you sure?", e.g. "yes, delete" and "no, keep it"

Last but not least, using "delete" and "cancel" buttons sound too similar, please choose clear naming. :)
