### ISSUE TITLE
User Story 37: Mobile Redesign

### ISSUE THREAD

**Issue by H-Alguen** [benediktbrenk/budget-app#88]
## Value Proposition

As a user
I want a better mobile friendly design,
so that I have an optimized user experience on my mobile devices.

## Description
no description

## Acceptance Criteria

- The design is responsive and optimized for mobile devices
- Navigation menus and buttons are large enough for touch interaction
- Content layout adjusts for different mobile screen sizes

## Tasks

- [ ] Create feature branch `feature/mobile-redesign`
- [ ] Change the order of components 
- [ ] Optimize content layout for mobile viewing
